# This example demonstrates all of the possible configuration elements
#
# Note that some of the attributes may not make sense in combination with other attributes
# and that this sample might not be runable as-is
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:
  # The platform version determines the desired version for all components, but those
  # can be overriden individually as well
  version: "0.2.2"

  targetNamespaces:
  - ns1
  - ns2

  appsodyOperator:
    # Overrides the platform wide settings for version on this component
    version: "0.2.0"

    # Overrides the image as a separate repository or tag
    repository: appsody/application-operator
    tag: "0.2.0"

    # Overrides the image uri
    image: appsody/application-operator:0.2.0

  cliServices:
    # Overrides the setting for version on this component
    version: "0.2.0"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-command-line-services
    tag: "0.2.0"

    # Overrides the image uri
    image: kabanero/kabanero-command-line-services:0.2.0

    # Indicates the token expiration time 
    # Specify a positive integer followed by a unit of time, which can be hours (h), minutes (m), or seconds (s). 
    # For example, specify 30 seconds as 30s. 
    # You can include multiple values in a single entry. For example, 1m30s is equivalent to 90 seconds.
    sessionExpirationSeconds: "1440m"

  landing:
    # The landing page is enabled by default. To disable specify false.
    enable: true 

  che:
    # che is disabled by default. Set the enable value to true/false to enable/disable the Che installation.
    enable: true

    kabaneroChe:
      # Overrides the platform wide settings for version on this component.
      version: "0.5.0"

      # Overrides the image as a separate repository or tag.
      repository: kabanero/kabanero-che
      tag: "0.5.0"

      # Overrides the image uri.
      image: kabanero/kabanero-che:0.5.0

    cheOperator:
      # Overrides the platform wide settings for version on this component.
      version: "7.2.0"

      # Overrides the image as a separate repository or tag.
      repository: quay.io/eclipse/che-operator
      tag: "7.2.0"

      # Overrides the image uri
      image: quay.io/eclipse/che-operator:7.2.0

    cheOperatorInstance:
      # Overrides the workspaceClusterRole to be used when deploying an instance of the Che CR.
      # The default workspaceClusterRole name is eclipse-codewind.
      cheWorkspaceClusterRole: eclipse-codewind

  collections: 
    # A list of those repositories which are searched for collections
    repositories: 
    - name: incubator
      url: https://github.com/kabanero-io/collections/releases/download/0.2.1/kabanero-index.yaml
      # Activates a default set of collections
      activateDefaultCollections: true
  # The information in the Github section is used by the Kabanero CLI to
  # perform user to role mapping when accessing the collection.
  github:
    # The API URL refers to the Github instance (or GHE instance) that
    # contains the organization where the collection was cloned.  The
    # CLI will use this URL to interact with Github (or GHE).
    apiUrl: https://api.github.com
    # The Github organization contains the repository where the
    # collection was cloned.
    organization: kabanero-io
    # The list of teams which should have admin authority to the
    # collection.  Each team must be defined in the Github
    # organization.  Members of the teams will be able to login to the
    # Kabanero CLI and administer the collection.
    teams:
    - adminTeam
