# Maps Kabanero platform version to related component versions
# understood by the other operators. 

# Note the following sequence: the Kabanero operator becomes aware
# of a new version of the Kabanero platform, in part by editing this file
# Once the operators are rolled out, the administrator can choose to use
# the new Kabanero version by editing the Kabanero resource. This causes
# other resources to be updated using this mapping

# When the Kabanero instance does not specify which version of Kabanero to use,
# this is the value
default: "0.2.0"

# Top level: relates Kabanero versions to software versions
kabanero:
- version: "0.1.1"
  related-versions: 
    appsody-operator: "0.1.0"
    cli-services: "0.1.0"
    landing: "0.1.0"
- version: "0.1.2"
  related-versions: 
    appsody-operator: "0.1.0"
    cli-services: "0.1.0"
    landing: "0.1.0"
- version: "0.2.0"
  related-versions: 
    appsody-operator: "0.2.0"
    cli-services: "0.2.0"
    landing: "0.2.0"
    che-operator: "7.2.0"
    kabanero-che: "0.5.0"
- version: "0.2.1"
  related-versions: 
    appsody-operator: "0.2.0"
    cli-services: "0.2.0"
    landing: "0.2.0"
    che-operator: "7.2.0"
    kabanero-che: "0.5.0"

related-software:
  appsody-operator:
  - version: "0.1.0"
    orchestrations: "orchestrations/appsody-operator/0.1"
    identifiers:
      repository: "appsody/application-operator"
      tag: "0.1.0"
  - version: "0.2.0"
    orchestrations: "orchestrations/appsody-operator/0.2"
    identifiers:
      repository: "appsody/application-operator"
      tag: "0.2.0"

  landing:
  - version: "0.1.0"
    orchestrations: "orchestrations/landing/0.1"
    identifiers:
      repository: "kabanero/landing"
      tag: "0.1.0"
  - version: "0.2.0"
    orchestrations: "orchestrations/landing/0.1"
    identifiers:
      repository: "kabanero/landing"
      tag: "0.2.0"

  cli-services: 
  - version: "0.2.0"
    orchestrations: "orchestrations/cli-services/0.1"
    identifiers:
      repository: "kabanero/kabanero-command-line-services"
      tag: "0.2.0"
  - version: "0.2.0-rc.1"
    orchestrations: "orchestrations/cli-services/0.1"
    identifiers:
      repository: "kabanero/kabanero-command-line-services"
      tag: "v0.2.0rc1"
  - version: "0.1.1-rc.1"
    orchestrations: "orchestrations/cli-services/0.1"
    identifiers:
      repository: "kabanero/kabanero-command-line-services"
      tag: "0.1.1-rc.1"
  - version: "0.1.1"
    orchestrations: "orchestrations/cli-services/0.1"
    identifiers:
      repository: "kabanero-io/kabanero-cli"
      tag: "0.1.0"
  - version: "0.1.0"
    orchestrations: "orchestrations/cli-services/0.1"
    identifiers:
      repository: "kabanero/kabanero-command-line-services"
      tag: "0.1.0"

  che-operator:
  # Compatible with kabanero-che version 0.5.0.
  - version: "7.2.0"
    orchestrations: "orchestrations/che/0.1"
    identifiers:
      repository: "quay.io/eclipse/che-operator"
      tag: "7.2.0"

  # kabanero-che deploys a specific version of Eclipse Che. The che-operator version
  # is in sync with the version of Eclipse Che installed by kabanero-che. 
  # If a newer version of kabanero-che installs a new version of Eclipse Che 
  # (kabanero-che:pom.xml), a new che-operator version entry is required.
  kabanero-che:
  # Uses Eclipse Che version 7.2.0,
  - version: "0.5.0"
    orchestrations: "orchestrations/che/0.1"
    identifiers:
      repository: "kabanero/kabanero-che"
      tag: "0.5.0"
